AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AddService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: addservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DelService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: delservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /delservice/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByID:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: getservicebyid.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getservbyid/{serviceid}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllServiceName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: getallservicenames.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallservname
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: updateservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updateservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetTrending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: gettrending.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettrend
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllTypes:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: getalltypes.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getalltypes
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: getservicebycategory.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettypes/{category}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllServices:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: getallservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallserv/{category}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetSliders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: getslider.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getslider
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetTabs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: gettabs.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettabs
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  SliderUploader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: sliderimguploader.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /sliderupload
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  SliderDeleter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: sliderimgdeleter.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /sliderdelete
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  TypeImgUploader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: typeimguploader.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /typeupload
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  TypeImgDeleter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/c6f6eb0c92f1515d5c0d751be47cbfbb
      Handler: typeimgdeleter.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /typedelete
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
