AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AddService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: addservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DelService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: delservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /delservice/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByID:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: getservicebyid.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getservbyid/{serviceid}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllServiceName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: getallservicenames.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallservname
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: updateservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updateservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetTrending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: gettrending.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettrend
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByType:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: getservicebytype.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getsubtypes/{gender}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByGender:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: getservicebygender.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettypes/{gender}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceBySubType:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: getservicebysubtype.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallserv/{gender}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  ImageUpload:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/476bf61dbfe96cbbd6125b952631a553
      Handler: file.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /imgupload
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
