AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AddService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: addservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DelService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: delservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /delservice/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByID:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: getservicebyid.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getservbyid/{serviceid}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllServiceName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: getallservicenames.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallservname
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: updateservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updateservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetTrending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: gettrending.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettrend
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByCategory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: getservicebycategory.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettypes/{category}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllServices:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: getallservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallserv/{category}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetSliders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: getslider.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getslider
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetTabs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: gettabs.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettabs
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  SliderUploader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: sliderimguploader.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /sliderupload
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  SliderDeleter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: sliderimgdeleter.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /sliderdelete
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  TypeImgUploader:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: typeimguploader.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /typeupload
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  TypeImgDeleter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/8af4f998046a57ec107e64ec0e877ea1
      Handler: typeimgdeleter.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /typedelete
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
