AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateNewLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/a7dde0302049b01978da3360c40d3edd
      Handler: createnewlog.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /newlog
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  CoinsIncrease:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/a7dde0302049b01978da3360c40d3edd
      Handler: coinincrease.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /coininc
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/a7dde0302049b01978da3360c40d3edd
      Handler: updatelog.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updlog
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
