AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateNewLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/1c853962114f55a38c6dd8592094a18c
      Handler: createnewlog.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /newlog
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
