AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateNewLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7b4704215e129210adac220aa043725a
      Handler: createnewlog.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /newlog
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  CoinsIncrease:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7b4704215e129210adac220aa043725a
      Handler: coinincrease.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /coininc
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DistanceModeToggler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7b4704215e129210adac220aa043725a
      Handler: distancemode.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /dismode
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7b4704215e129210adac220aa043725a
      Handler: updatelog.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updlog
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  ServiceEndOtpAccept:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7b4704215e129210adac220aa043725a
      Handler: endservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /acceptendserv
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  ServiceStartOtpAccept:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7b4704215e129210adac220aa043725a
      Handler: startservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /acceptstartserv
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
