AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  CreateNewLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/aadd4a6f4da0af53da0d77c7807a0583
      Handler: createnewlog.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /newlog
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  CoinsIncrease:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/aadd4a6f4da0af53da0d77c7807a0583
      Handler: coinincrease.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /coininc
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
