AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  myDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  myCart:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Carts
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: serviceId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: serviceId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  myServices:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Services
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  BarberLog:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: BarbersLog
      AttributeDefinitions:
      - AttributeName: date
        AttributeType: S
      - AttributeName: barberId
        AttributeType: S
      KeySchema:
      - AttributeName: date
        KeyType: HASH
      - AttributeName: barberId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  myBookings:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bookings
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: serviceId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: serviceId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ProfileUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/90ae59b2737686c950f94db8af7cd04a
      Handler: users.profileupdate
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /profileupd
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/90ae59b2737686c950f94db8af7cd04a
      Handler: users.addupdate
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /address
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/90ae59b2737686c950f94db8af7cd04a
      Handler: users.getuser
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getuser
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  LoginPhone:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/90ae59b2737686c950f94db8af7cd04a
      Handler: users.loginphone
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /loginphone
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  LoginOtp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/90ae59b2737686c950f94db8af7cd04a
      Handler: users.loginotp
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /loginotp
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddtoCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/5394ef45b770c4fa43416ef5090f15c4
      Handler: cart.addtocart
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addtocart/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/5394ef45b770c4fa43416ef5090f15c4
      Handler: cart.getcart
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getcart
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  Quantity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/5394ef45b770c4fa43416ef5090f15c4
      Handler: cart.quantity
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /quantity/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteFromCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/5394ef45b770c4fa43416ef5090f15c4
      Handler: cart.deletefromcart
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deletefromcart/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.addservice
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DelService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.delservice
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /delservice/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByID:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.getservicebyid
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getservbyid/{serviceid}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllServiceName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.getallservicenames
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallservname
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.updateservice
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updateservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetTrending:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.gettrending
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettrend
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByType:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.getservicebytype
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getsubtypes/{gender}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceByGender:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.getservicebygender
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /gettypes/{gender}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetServiceBySubType:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/49e86c3d1db43f76b3426c58f0dc07af
      Handler: service.getservicebysubtype
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallserv/{gender}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  LocationUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e72fdab64cf9f3dad6754927153b060b
      Handler: barber.locationupdate
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /locupd
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  CreateNewLog:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e72fdab64cf9f3dad6754927153b060b
      Handler: barber.createnewlog
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /newlog
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetBarbersByDate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7795026c25be8a9bb60cfb945aee4936
      Handler: booking.barberbyslot
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getbarb/{date}/{slot}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  BarberSelect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7795026c25be8a9bb60cfb945aee4936
      Handler: booking.selectbarber
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /book/{date}/{slot}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetBookings:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7795026c25be8a9bb60cfb945aee4936
      Handler: booking.getbookings
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getbookings
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
