AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  myDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  myCart:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Carts
      AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: serviceId
        AttributeType: S
      KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: serviceId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  myServices:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Services
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  BarberLocation:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Barbers
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  Register:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/82a62cae94bf86dd945bfa521ce7817d
      Handler: users.register
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /register
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/82a62cae94bf86dd945bfa521ce7817d
      Handler: users.addupdate
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /address
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  LoginPhone:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/82a62cae94bf86dd945bfa521ce7817d
      Handler: users.loginphone
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /loginphone
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  LoginOtp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/82a62cae94bf86dd945bfa521ce7817d
      Handler: users.loginotp
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /loginotp
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddtoCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/505b88507659e5cac3fa86abde7fb1da
      Handler: cart.addtocart
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addtocart/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/505b88507659e5cac3fa86abde7fb1da
      Handler: cart.getcart
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getcart
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  Quantity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/505b88507659e5cac3fa86abde7fb1da
      Handler: cart.quantity
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /quantity/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteFromCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/505b88507659e5cac3fa86abde7fb1da
      Handler: cart.deletefromcart
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deletefromcart/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/62a35a79ec423ce5d11e5d2888c914fa
      Handler: service.addservice
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addservice
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DelService:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/62a35a79ec423ce5d11e5d2888c914fa
      Handler: service.delservice
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /delservice/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  LocationUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-bucket/980cf89201fb6ef00e347c24811eb5dd
      Handler: barber.locationupdate
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /locupd
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
