version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Barbera"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bvt3026gh790"
s3_prefix = "Barbera"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
