AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ProfileUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: profileupdate.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /profileupd
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  AddressUpdate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: addressupdate.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /address
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: getuser.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getuser
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  LoginPhone:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: loginphone.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /loginphone
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  LoginOtp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: loginotp.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /loginotp
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  ServiceEndOtp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: endservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /endserv
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  ServiceStartOtp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/f059c2a382d378fd415ca19f72d9b68b
      Handler: startservice.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /startserv
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
