AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetReferralCode:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: getreferral.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getref
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  CouponCreate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: couponcreate.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /couponcreate
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  UseCoupon:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: availcoupon.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /usecoupon
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllCoupons:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: getallcoupons.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getallcoupons
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetCoupon:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: getcoupon.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getcoupon/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteCoupon:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: deletecoupon.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /delcoupon
            Method: delete
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateCoupon:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b24f1f4cbee4fe1ec51861f2c6e588d4
      Handler: updatecoupon.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updcoupon/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
