AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Stack-Name: Barbera-Bookings
  # Hostname: https://k84yh5ra7g.execute-api.ap-south-1.amazonaws.com/Prod

  #---------------------------------------------------------------
  # Booking Functions
  #---------------------------------------------------------------
  GetBarbersByDate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: barberbyslot.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /getbarb/{date}/{slot}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  BarberSelect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: selectbarber.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /book/{date}/{slot}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  GetBookings:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getbookings.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /getbookings
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  GetBookingsForBarbers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getbookingsbarb.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /getbookbarb
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  DeleteFullCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: deletefullcart.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /deletecart
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------




            
  