AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetBarbersByDate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/11a81f392d6fb110ae9ea01cba93228f
      Handler: barberbyslot.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getbarb/{date}/{slot}
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  BarberSelect:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/11a81f392d6fb110ae9ea01cba93228f
      Handler: selectbarber.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /book/{date}/{slot}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetBookings:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/11a81f392d6fb110ae9ea01cba93228f
      Handler: getbookings.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getbookings
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteFullCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/11a81f392d6fb110ae9ea01cba93228f
      Handler: deletefullcart.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deletecart
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
