AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BookSlotWise:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: bookslot.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /bookslot/{date}/{slot}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  InstantBooking:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: bookinstant.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /bookinst
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  ConfirmBooking:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: bookconfirm.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /bookconfirm
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  RevertBooking:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: bookrevert.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /bookrevert
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  CancelBooking:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: cancelbooking.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /bookcancel
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetBookings:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: getbookings.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getbookings
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetBookingsForBarbers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: getbookingsbarb.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getbookbarb
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteFullCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/b517b09949514ae4a7355145f7bfef00
      Handler: deletefullcart.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deletecart
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
