AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # Stack-Name: Barbera-Offers
  # Hostname: https://ngqdvnidwf.execute-api.ap-south-1.amazonaws.com/Prod

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS, DELETE'"
        AllowHeaders: "'X-Forwarded-For,Authorization,Content-Type'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
        AllowCredentials: false

  #---------------------------------------------------------------
  # Offer Functions
  #---------------------------------------------------------------

  CreateOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: createoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /createoffer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  UpdateOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: updateoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /updateoffer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  DeleteOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: deleteoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /deloffer
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  GetAllOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getalloffers.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /getalloffer
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------

  GetOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: getoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api 
          Properties:
            Path: /getoffer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  #---------------------------------------------------------------
  
