AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS, DELETE'''
        AllowHeaders: '''X-Forwarded-For,Authorization,Content-Type'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  CreateOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e3fc1b5d8dc0fc7acd5e4d027119bc88
      Handler: createoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /createoffer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  UpdateOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e3fc1b5d8dc0fc7acd5e4d027119bc88
      Handler: updateoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /updateoffer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e3fc1b5d8dc0fc7acd5e4d027119bc88
      Handler: deleteoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deloffer
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e3fc1b5d8dc0fc7acd5e4d027119bc88
      Handler: getalloffers.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getalloffer
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetOffer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/e3fc1b5d8dc0fc7acd5e4d027119bc88
      Handler: getoffer.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getoffer
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::140544830924:role/BackendUser
