AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SendMail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/99a6056ec4494816b278f33616db3895
      Handler: sendmail.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /sendmail
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetAllBarberLogs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/99a6056ec4494816b278f33616db3895
      Handler: getbarberlogs.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getlogs
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
