AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SendMail:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/7f9f790eaa0bd6368592ddfdde873754
      Handler: sendmail.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /sendmail
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
