AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AddtoCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/388e2df803b92c73ad804ee2f06ddf33
      Handler: addtocart.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /addtocart
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  GetCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/388e2df803b92c73ad804ee2f06ddf33
      Handler: getcart.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /getcart
            Method: get
      Role: arn:aws:iam::140544830924:role/BackendUser
  Quantity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/388e2df803b92c73ad804ee2f06ddf33
      Handler: quantityupdate.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /quantity
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
  DeleteFromCart:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://barbera-buckets/388e2df803b92c73ad804ee2f06ddf33
      Handler: deletefromcart.handler
      Runtime: nodejs12.x
      Events:
        apiForLambda:
          Type: Api
          Properties:
            Path: /deletefromcart/{serviceid}
            Method: post
      Role: arn:aws:iam::140544830924:role/BackendUser
